### PR TITLE
Changes private declarations to protected

### PR DESCRIPTION
**Pull request by alandsidel**
Will, this pull request:
- Changes all private methods and properties to protected.  This allows overriding class behavior locally without having to touch the lib source.
- Raises beta version of all touched files by one.
- Raises overall version (via flourish.rev) to 0.9.1 from 0.9.0

### CODE REVIEW

**Comment by alandsidel** [comment]
Oh, I omitted fUTF8 as it was not properly displaying in my editor and I didn't want to risk damaging the file.  I think all that needs done is a proper UTF8 signature added to the file itself, since it contains UTF8 characters.

**Comment by mattsah** [comment]
Alan,

I understand and appreciate your aim with this (as in my mind there are a lot of things that should be opened up in Flourish), however, I do not feel that this is the solution.  The problem here is that the parent class should (not always) but frequently be a determining authority on the state of the object.  This is particularly true when we're talking about properties on classes as opposed to methods which will either provide access to those properties or perform actions using them in some ways.

The problem here (as many people tend to think it is with private vs. protected debate) is not that we are trying to force your extending class to do things a certain way, but that we're trying to prevent your extending class from breaking ours.  Futhermore, protected properties in classes (particuarly static ones since objects have their own state), means you start to get a lot of difficulty finding things... the scope and context of information could hypothetically span X number of files where X is necessarily greater than 1 vs. private where it is certainly only ever in the class which has that authority.

I don't want to sound harsh, but this is the kind of thing that if incorporated in Flourish, would make me stop using it or at least taking my fork in a completely different direction.

**Comment by alandsidel** [comment]
"we're trying to prevent your extending class from breaking ours"

Honestly, this sounds like "my problem" to worry about, not yours.  If I break something, I can fix it.  As it stands right now, I cannot fix things in the core lib without directly hacking on it -- which is something I am avoiding doing at all costs, and have instructed my team similarly.  We want to be able to keep up with updates to the lib without having to worry about "remembering" our local changes and going through a painful merge process to ensure they (or at least their functionality) is kept.

The solution to this problem is for us to never modify the vanilla files and instead to extend and override their behavior in our own descendant classes.  The overly prolific use of private declarations does not allow us to do this.

At the moment I'm tracking down a memory leak in fRecordSet.  I found a similar one in fActiveRecord some time back, where memory is not freed when a record is unset/nulled/goes out of scope because a reference to it still exists in the fActiveRecord::identity_map (which is static).  Our solution was to contact Will with the issue (a few months ago) and then, while waiting on an official fix, extend fActiveRecord into a new class and add a "free" method which nulls and unsets the entry in the identity_map.

I have a feeling I will need to do something similar with fRecordSet but simply cannot with the interface so "locked down" via private declarations.

At the risk of making the code somewhat messy, but alleviating your concerns (which I don't share or even really understand), some sort of 'debug mode' define would work for me, with ifdef's sprinkled everywhere to change the private/protected declarations depending on the state of the flag.

Your closing statement didn't sound harsh, it sounded more like an ultimatum or "threat" if you will, which leaves me entirely perplexed.  If you (or your team) are introducing bugs in your descendant classes by overriding things in a way that makes them non-functional, that's no reason to hobble everyone else who gets a benefit from overriding without introducing bugs.

**Comment by mattsah** [comment]
Allen, all due respect, when I said "your extended class" I didn't specifically mean yours.  I was using "your" in the anonymous and plural sense.

The point is simple.  Let's say I have a system based on flourish, and I import 2 additional libraries that use or extend flourish in some way.  If one of them doesn't do something properly and causes the other one, or Flourish itself to no longer operate properly because let's say it's sticking a scalar value into something Flourish expects to be an array, this can be a hell of a thing for me to debug.

I would be difficult for me to determine whether it's Flourish, Library A, or Library B.  If this was the developer experience I'd imagine people would reject it at the sight of such issues.

Flourish having moved to github means that we have a much better, more public, and less decentralized version control system than previously.  I see no reason why you could not maintain a fork of Flourish which makes core changes (not necessarily making everything private protected) and merge upstream flourish when Will makes updates.  In my mind, the occasional conflicting merge would cause severely less headaches than would the free-for-all that might be caused by not enforcing any state integrity of the classes.

If you have a fix for the fActiveRecord issue you note, my suggestion would be to submit that fix as a pull request, thereby influencing the official core classes in a positive fashion for all.

I did not intend it to be harsh _or_ a threat... what I intended was simply that I use Flourish because it is properly developed and understands why the above mentioned integrity is important (compared to other libraries, frameworks, etc that make everything public) for example.

Of course you can make everything public, protected, whatever really and if someone other than you screws it up you can point the finger.  But really who wants to deal with a library in such a state?

Keep in mind that you can add logic by overloading a method but still use the logic of the parent class.  I.e. You can always do some initial logic in the overloaded method, then call parent::whatever() then do some followup logic.  If this is not suitable because the proper injection point is somewhere in the middle of the parent's logic I would suggest forking, implementing a hook of some sorts at that point, and then writing a callback to interject at the point of that hook -- this would be a much cleaner and extensible solution for all.

**Comment by alandsidel** [comment]
"Let's say I have a system based on flourish, and I import 2 additional libraries that use or extend flourish in some way. If one of them doesn't do something properly and causes the other one, or Flourish itself to no longer operate properly because let's say it's sticking a scalar value into something Flourish expects to be an array, this can be a hell of a thing for me to debug."

It can be, but that is your (the royal you, as well) "problem".  It's up to you to look over the libs you intend to use, especially if they're extending core classes, and to also have test cases to catch things like that.  The private interface does insulate you somewhat from having to perform this "due diligence" but only conceptually.  In practice, any one of the existing public or protected interfaces can be overridden in a way that causes such problems.

Again, I'm willing to make the changes to add an IFDEF check, defaulting to the _protected_ interface, but switching to private if the flag is set.  This may sound backwards to you, but it's actually the only way to meet your goal.  If the flag defaults to private, then any lib can set the flag and put you back at square one.  If it defaults to protected, libs have no reason to set the flag, and you can set it in your own project to "catch out" libs that need the changed interface.

If it comes down to me maintaining a real fork of the project because this pull request isn't taken, I have a feeling this would eventually lead to the "death" of the project (if it's not already dead, it seems to be, or close).  One popular lib that required the protected interface is all it would take to "kill" the private version.  That's not something I'd like to see happen.

**Comment by mattsah** [comment]
> It can be, but that is your (the royal you, as well) "problem".

And why should Flourish encourage that problem?

> In practice, any one of the existing public or protected interfaces can be overridden in a way that causes such problems.

This is simply not true.  I do not know of a single instance really where Flourish has a non-private property.  Where things should and need to be overloaded, accessor methods are provided to do so.  Those accessor methods have the requisite logic to ensure the integrity of those internal properties.  The private interface insulates you practically, that is precisely what it is designed to do, simply because I can modify Flourish's code to change private to protected does not mean it is conceptual difference only.  So long as it is private, no class will be able to @#$% up those internal states EXCEPT Flourish classes.  The moment you change that, where and/how it got @#$%ed up is anyone's guess.

> Again, I'm willing to make the changes to add an IFDEF check, defaulting to the protected interface, but switching to private if the flag is set. This may sound backwards to you, but it's actually the only way to meet your goal. If the flag defaults to private, then any lib can set the flag and put you back at square one. If it defaults to protected, libs have no reason to set the flag, and you can set it in your own project to "catch out" libs that need the changed interface.

This is, in my opinion, a terrible, confusing, and far too verbose solution, and I'm not even quite sure how it could be practically implemented in a clean way (at least not dynamically as you seem to be proposing).

There are far better solutions for extending and modifying behaviors which Flourish employs in many cases already, including places to register custom callbacks, and a number of called hooks.  I don't know or understand the depths of your particular requirements for doing this... from what you stated above, I see no reason why you can't or wouldn't submit a pull request with an actual patch for the _problem_ you found, rather than submitting a patch to make everything public/protected so you could maintain the forked and fixed version yourself.

**Comment by mattsah** [comment]
Let me point out that if any of your arguments were valid, why wouldn't you just switch everything to public?  Afterall, any of the consequences would be your (the royal you) "problem".  Furthermore, switching protected stuff to public makes sense, why should only an extending/inheriting class be able to call certain methods and/or modify certain properties?

**Comment by khamer** [comment]
@alandsidel – my biggest reason to avoid this is that it locks down the implementation of each class further by increasing the API significantly. While the API hasn't changed significantly for while, some of the work iMarc has done has affected a lot of the internals of fFile/fFilesystem/fImage, for example. @wbond has been supportive of making changes to make sure that subclasses can be used (for example, rev 1.0.0b22 of fTemplating) with Flourish.

You could always look into something ReflectionMethod (with 5.3.2) for things like unit tests or debugging.

**Comment by alandsidel** [comment]
@mattsah

I am at a loss.  Private does not "protect" you, or your developers, from anything.  If I give you a class called "classB" that extends classA, I have two options.  I can override just the protected/public parts I need to, and provide a small, simple class.  That's option A, and it works if everything I need to override is exposed.  Option B, where everything is "locked down" via private interface(s), is just as simple.  The only difference is that in order to override the private stuff, I need to also "override" (copy and paste, with no changes) every method that uses whatever private thing I've overridden.

You give the impression that you believe I _cannot_ override private methods or properties, and that simply isn't true.

I have a hard time believing that debugging a problem in one where 'foo' was changed from one type to another is any harder than in the other.  If you want to point fingers here, point them at PHP for not having strong type checking or forcing vars to be declared before use.  I do, daily.

In the end, what have you gained by making things private?  As far as I can tell, nothing.  If some "jerk" comes along and overrides a bunch of stuff in the extended class, you can't stop it by waving the "private" wand, and debugging scenarios like you suggest are just as difficult, if not moreso, since now you have to look for changes in many more functions/properties rather than those the developer wanted to override in the first place.  In the example above, if I changed some private property from one type to another, you think that would be _easier_ to find?

> Let me point out that if any of your arguments were valid, why wouldn't you just switch everything to public?

Public establishes the contract with unrelated code and classes that want to _use_ your class.  Protected establishes the contract between your class and those that want to extend it.  Private simply stands in the way of extending (vs protected).  I have (almost) never used a private declaration in the 20 years I've been coding.  It's easier on everyone if you define the interface spec elsewhere, like in the documentation and/or comments (or, _gasp_, an interface spec).  If something is dangerous to modify from the outside, then you slap big bold letters in the comments saying so, and you name the method or property accordingly.  Prefix it with 'int' or 'priv' or something.  Trying to "lock out" other developers is a waste of time.  Worrying about "what if" scenarios only holds water if the solution prevents those scenarios -- and in this case, it doesn't.

> I see no reason why you can't or wouldn't submit a pull request with an actual patch for the problem you found, rather than submitting a patch to make everything public/protected so you could maintain the forked and fixed version yourself.

Wow.  That is not my goal at all.  I fixed the problem locally and emailed it to Will months ago, before he the code moved to github.  It still hasn't made it in.  When I ran into another similar bug, and was once again faced with this wall of private declarations, I decided to address the issue.  I saw that the code had moved to github, and decided that since I was making the change locally anyway (to change private to protected) that I may as well do it here and send the pull request.  If my goal was to "maintain the forked and fixed version myself" I would not have sent him that patch (which is lost or ignored I guess), nor would I have bothered to fork on github and send in this pull request.  I would have simply kept working privately, not "giving back".

Now, if this pull request does not make it into the lib, then I will maintain the fork I made indefinitely, because (as should be obvious by now) I am not going to be convinced that private declarations are a good idea.  They only "protect you" from yourself, and that's not the kind of protection I need.

@khamer

It's not unit tests and so on that these declarations are causing me to bump my head against, it's debugging actual functionality problems (most of the time) and extending when I need to the rest of the time.  As I said initially, I have a "standing order" within my small team to not touch the core flourish code, or any other 3rd party library we use.  The rule is to extend classes and then use the extended classes.  This has been problematic lately with flourish because:
1. The prolific use of private.
2. In some cases, things like fClass::blah are used rather than self::blah or $this->blah.  In these cases, even when I do override a public or protected method, other methods still call the wrong one.  These are next on my 'todo' list when it comes to fixing.

**Comment by mattsah** [comment]
> In the end, what have you gained by making things private? As far as I can tell, nothing. If some "jerk" comes along and overrides a bunch of stuff in the extended class, you can't stop it by waving the "private" wand, and debugging scenarios like you suggest are just as difficult, if not moreso, since now you have to look for changes in many more functions/properties rather than those the developer wanted to override in the first place. In the example above, if I changed some private property from one type to another, you think that would be easier to find?

You're missing the point.  If it's private and some idiot overloads it in their library and it stops working, I KNOW IT IS IN THEIR LIBRARY AND ONLY THEIR LIBRARY IS BROKEN BY IT.

I'm not claiming that you cannot overload a private property or method, but contrary to your claim you absolutely DO NOT have to copy every single private property and method to extend a class -- you only would really need to do that if you want to replace the class outright.  I'm all for making methods which should be accessible via extension protected, which, in order to modify private properties would have to call the parent method, thereby ensuring that Flourish can do it's requisite checks and validate and/or transform the data in the appropriate way so that other methods and classes relying on it aren't shattered by someone deciding that a property, for example, would be better as a string separated by ':' than an array which they think is fine to explode and implode all the time.

**Comment by mattsah** [comment]
My last and final word on this issue: http://scriptogr.am/mattsah/post/understanding-the-three-ps-and-one-big-fu

**Comment by pjbeardsley** [comment]
Not really here to voice an opinion (would rather hear what Will has to say), but I would just like to point out that the "memory leak" @alandsidel refers to is a known issue with fActiveRecord on memory-constrained servers.

It's not a memory leak in the traditional sense (no cyclical references or other known causes of PHP reference count failure).  I would describe it as "overzealous caching".

Will helped me develop a "band aid" fix—a public method to manually purged the memory map, which which was called when processing large recordsets.

Eventually we moved to a beefier server and I was able to revert to stock Flourish without issue.  Since the server I was on was truly horrible and we were processing an abnormally large amount of data, I moved forward with the assumption that it was an outlier.

Since this is a practical issue that others have apparently run into, I would suggest opening a ticket to make identity map purging part of the fActiveRecord API rather than rolling your own.

**Comment by alandsidel** [comment]
@mattsah Oh noes, angry blogger is angry.  Why not just move to RoR?  You'll fit in better.

@pjbeardsley the fix was pretty simple, tracking it down was the pain in the rear, but what I did in the extended class is probably similar to the fix you worked out with Will.  This is in my extended fActiveRecord class:

```
public function free()
{
  $class = get_class($this);
  $hash = self::hash($this->values, $class);
  if (array_key_exists($class, self::$identity_map))
  {
    if (array_key_exists($hash, self::$identity_map[$class]))
    {
      self::$identity_map[$class][$hash] = null;
      unset(self::$identity_map[$class][$hash]);
    }
  }
}
```

Calling free() before the fAR goes out of scope removes it from the static cache, freeing the reference and allowing PHPs GC to do it's job.  Of course I need to have fRecordSet call the function as well, so I extended that into a new class and created a destructor.

```
function __destruct()
{
  if ($this->records)
  {
    if (is_array($this->records))
    {
      foreach ($this->records as &$record)
      {
        $record->free();
        $record = null;
      }
    }
  }
}
```

This necessitated exposing the fRecordSet::records property (as protected) in order for the extended class to access it in the destructor, and overriding fRecordSet::build as well to use the new activerecord class.  This started a small avalanche of changes as fORMRelated calls fRecordSet::build in buildRecords, which itself is called back in fActiveRecord, etc.

It would have been far easier to put this code into the fRecordSet and fActiveRecord classes directly, rather than overriding the behavior, but I expected Will to come up with a more elegant solution for core after contacting him about it (like a knob to just disable caching -- I have enough caching as it is) and figured once that was done, I could simply empty out my extended classes to get back to vanilla flourish.  The first bug or two I contacted him about, he responded quickly; but the last response I got was perhaps 6-8 months ago.  He hasn't weighed in on this topic either, obviously.  The last ticket I opened @ the flourish site was 4 months ago and has had no response.

Hoping he will return to active development on flourish, but realizing he may not, extending the core classes is the easiest way to get the functionality we need.  In this case, that functionality is simply letting these objects behave as expected -- releasing their memory when they are freed or go out of scope -- rather than silently attempting to cache them.

This is not a problem just on 'small, underpowered' servers, it's a problem on any server where you're working with large amounts of data.  Giving PHP more memory so it can process all the records now, with the caching, is not a solution -- as the number of records we need to process grows, we'll just run into the wall again.  Eventually, it won't fit in the physical 64G of memory the server has.

**Comment by wbond** [comment]
Preface:

I feel like the tone of this conversation is getting overly combative, and I don't think it is helped by the desensitizing nature of the internet. I'd like the keep the Flourish community headed on more of a level of friendly and constructive disagreement.

---

The way Flourish is designed with lots of private methods and attributes is specifically done on purpose. One of the goals of Flourish is good documentation and making it very clear what changed and documenting every single backwards compatibility break (http://flourishlib.com/docs/BackwardsCompatibilityBreak and http://flourishlib.com/docs/InternalBackwardsCompatibilityBreak) so that code can be updated.

This change would more or less make it impossible to do so in the future, in that documentation would have to be written to the majority of commits, and would increase the noise in the Backwards Compatibility Breaks page immensely. Having a very clear and purposeful "public" API is important to me, and this would drastically change it.

There are other reasons, which Matt has alluded to, such as debugging. While you may see it as your problem if something breaks, inevitably users come and email me or post a bug report or on the forum if something is broken. The more exposed the innards are, the more likely time is wasted because end-user developers don't have a complete mental picture of how the innards work.

If there are a few places where private declarations are hobbling extensibility, I am more than happy to discuss the merits of opening those up, but I do not want to take a shotgun approach to this.

---

One note: because of the way that PHP is implemented, static properties will always reference the defining class. Calling self::$property instead of fCore::$property will make no difference. This is one of the downsides of static classes. In most cases in Flourish this is used in situations where a single implementation make the most sense to the majority of developers. I'm sure there can be improvements made in places.

---

In terms of fActiveRecord, I chose to implement the identity map so that users of the ORM would not be surprised if user 2 was loaded in two different scope and modified in one, that the changes would be present in the other. To do this, there needs to be a global registry of the active record models. This global registry can be cleared by calling fActiveRecord::clearIdentityMap(). I can say that the ORM will definitely run much more slowly for batch processing records that an unbuffered query will, simply due to all of the automatic coercing, hooks, etc. Additionally it will use a bit more memory, especially due to the massive memory size of arrays in PHP. This is due to the convenience functionality such as tracking old versions of attributes, caching related records, etc.

That said, I'm certainly not ruling out the addition of a way to turn off the identity map. I can see how that would be useful in certain circumstances.

---

In terms of me being involved in active development in Flourish, there are a couple of things holding me back right now. If users do have an interest in helping, there are two main infrastructure related items that need to be solved before I can move on to trying to get more people involved with the project. I'll likely write a short blog about this soon and link to it via twitter to try and rally some more help.
1. Finish moving the tickets from flourishlib.com to github. If anyone can help moving some of the tickets that have not been ported yet, that would be a huge help. If you are going to help, please copy the original ticket along with comments (referencing usernames) into a github ticket. Attachments should be posted as fenced code blocks in the GFM. Once the ticket is copied, please post the github URL of the ticket into a comment on the flourishlib.com ticketing system.
2. The forum needs to be ported from the Trac (python) implementation it is right now to a Flourish-based PHP implementation using GitHub Oauth for authentication. This will allow me to kill the old Flourish server and focus more of my time on getting people involved with bugs fixes, docs, enhancements etc.

I foresee myself taking more of a facilitator role moving forward rather than trying to do it all myself. Unfortunately the time in my life where I can spend 3 hours a night performing all of the duties on an open source project has passed. That combined with other open source and commercial hobbies means that I need to get other involved to ensure that Flourish continue to… flourish. Hah!

So, if anyone reading this is interested in helping out, feel free to start copying tickets, or shoot me an email about working on the forum.

**Comment by alandsidel** [comment]
Thanks for the response, Will.

> I feel like the tone of this conversation is getting overly combative, and I don't think it is helped by the desensitizing nature of the internet

Absolutely.  Apologies for my part.

> That said, I'm certainly not ruling out the addition of a way to turn off the identity map

A knob to disable the identity map would be very nice.  I'm not concerned with other instances of the class being made aware of changes in such cases.  Since zval's can't be determined without xdebug, and an internal ref counter would be difficult to decrement properly, this is probably the only way.

As it stands I have no choice but to either do the 'free()' thing I outlined above (in an extended class or in the core), or batch process groups of records in different processes to 'force' the cache to clear.  I was surprised this behavior is not (or not well, depending on if it's there vs. how hard I looked) documented.  When I first ran into memory exhaustion I thought it was due to fRecordSet pulling all the records, so I looked into using a cursor but found no support.  From there I decided to pull with a limit in batches of 1000, ensuring that the recordset went out of scope and was freed.  I was surprised when I found that even this didn't help the memory footprint, and was "forced" to go diffing for what I assumed to be a leak.

> because of the way that PHP is implemented, static properties will always reference the defining class. Calling self::$property instead of fCore::$property will make no difference

This isn't true, at least not in 5.4.  I don't know if that's a bug that was fixed or if you mean something else, but this:

```
class classA
{
  static private $foo;

  static public function setFoo($val)
  {
    self::$foo = $val;
  }

  static public function getFoo()
  {
    return self::$foo;
  }
}

class classB extends classA
{
  static private $foo;

  static public function setFoo($val)
  {
    self::$foo = $val;
  }

  static public function getFoo()
  {
    return self::$foo;
  }
}

classA::setFoo('bar');
print('A = '.classA::getFoo()."\n");
classB::setFoo('baz');
print('A = '.classA::getFoo()."\n");
print('B = '.classB::getFoo()."\n");
```

prints this:

```
A = bar
A = bar
B = baz
```

Which is as expected.  Changing the private to protected in A and dropping it from B also performs as expected:

```
A = bar
A = baz
B = baz
```

Perhaps I misunderstand your meaning.

> If there are a few places where private declarations are hobbling extensibility, I am more than happy to discuss the merits of opening those up, but I do not want to take a shotgun approach to this.

Will close the pull request after others have had a chance to respond, if they are so inclined.

**Pull request closed without merging**
