### PR TITLE
Changes to Flourish

### PR DESCRIPTION
**Pull request by mattsah**
Hey Will, this is a single commit which patched a full clean slate fork of your flourish-classes repository with all the .inK changes.  Unfortunately, this commit does contain whitespace changes.  I assume with a pull request you need to select pretty much all or nothing, but perhaps you can do more selective merging.  I've never actually done one, so I'm not sure, but either way, aside from all trailing whitespace being stripped here's the changes as have been noted in multiple places:
- Added fJSONSerializable non-native implementation support
- Made CSS/JS compression in fTemplating use PHP to include (i.e. you can put PHP in CSS and JS if it's compressed)

One of the more recent changes is to fix issue #69 on the issues list for your repo.  I looked through the code and realized it was just a matter of trimming the content type of whitespace to ensure RegEx matches worked properly.
- Fixed bug in fRequest so that types are trimmed for proper RegEx matching

Take what you want, none at all, or just copy the bugfix manually for all I care, I'll deal with the merging from upstream on my fork down the line if you don't want to pull the full commit.

### CODE REVIEW

**Comment by Tatsh** [comment]
Can't agree with JSONSerializable support just yet as that is 5.4+ only and the syntax doesn't allow this to be added conditionally and still cache well (APC doesn't like conditionally defined classes).

I think the 'namespaces' branch of Flourish should begin soon for 5.4+ (I know namespaces were introduced in 5.3) and this is where JSONSerializable support can be added.

I'm not really into the standard but I have a feeling static classes are going to bite us later on when it comes to decoupling.

**Comment by mattsah** [comment]
@tash JSONSerializable is an interface.  Furthermore, it does not need to be conditionally included.  This does not actually add the interface to flourish, but allows you to create the interface in your own projects in PHP < 5.4.  All this does is determine whether or not the interface is available and if you're on a version less than 5.4 sets the value in JSON::encode to the output of the method's output if the class implements it.  The relevant code is below and is the only change related to it.  Again, whether or not you include the interface, or how you load it statically or dynamically, is up to you.  If you don't have it, it simply won't be used.  If you do, it will determine if it needs to be called manually.

```
+

+      $is_scalar             = (!is_object($value) && !is_array($value));

+      $has_json_serializable = interface_exists('JSONSerializable');

+

+      if ($is_scalar || !$has_json_serializable || fCore::checkVersion('5.4')) {

+        //

+        // Versions of PHP >= 5.4 have a native JSONSerializable interface so we can

+        // natively encode scalars, systems without that interface at all, or those which

+        // would have it natively.

+        //

+        return json_encode($value);

+      }

+

+      if (is_object($value) && $value instanceof JSONSerializable) {

+        $value = $value->jsonSerialize();

+      }
```

**Comment by mattsah** [comment]
I should note, the only downside of it is that objects and arrays are manually encoded by Flourish if you do implement and don't have PHP 5.4.  This ensures that arrays of arrays or objects with child objects that are JSON serializable will be handled properly.  Keep in mind that this does not mean _all_ the child members will be manually encoded, as it will still call recursively and any scalar values will still undergo native encoding.

**Comment by mattsah** [comment]
Also, on the issue of namespaces, I believe flourish should avoid them until PHP fixes their many problems:

http://pornel.net/phpns

**Comment by Tatsh** [comment]
Okay. I'll agree on namespaces (yet again). Let's retain 5.1+ compatibility and it looks like this change is fine overall.

We really should come to an agreement regarding standards or Flourisg files should have mode lines (vi and Kate mode lines).

**Comment by wbond** [comment]
I'm not trying to discourage submitting pull requests, but this is kind of a mess right now. A single pull request with 10,000 lines of changes which include a mix of whitespace changes and code is not something I am going to shotgun merge.

I am ok with changing the whitespace style of the project to auto-trim whitespace, but it should be done in a single commit without any functional changes.

The smaller commits look better, and as soon as I finish up some of the last migration items, we can start merging these and closing the applicable issues.

**Comment by wbond** [comment]
Honestly, I'm never going to have the time to go through and try to sort this all out. The larger the pull request, the more time in one sitting I need to review it all. If you can break the pull requests into logical chunks, then I can take a stab at them.

In terms of whitespace changes, since lots of developers now auto-trim whitespace I am going to need to make this commit and we'll have to deal with the side effects on patches.

**Pull request closed without merging**
