### PR TITLE
misc changes

### PR DESCRIPTION
**Pull request by cidic**
fORMFile.php 
added function to check if a column has been configured as a file upload column

fPagination.php
added ability to set the page number query param name

### CODE REVIEW

**Comment by jeffturcotte** [comment]
The fPagination enhancement is good, but perhaps it should be per-template?

As for fORMFile, the functionality for determining whether a column has been configured as a file upload is already available through the inspect callback. 

``` php
# will return an array with the fORMFile metadata.
MyClass::inspectMyColumn() 
```

Look at `fORMFile::inspect` to see how the inspect metadata is augmented. It will show if it's a file or image, and you can also get back the destination directory for the file. 

IMO the inspect metadata should be namespaced with the string 'fORMFile', not 'feature', and namespacing by class should be a standard across the board going forward.

**Comment by mattsah** [comment]
@jeffturcotte 

The problem as I see it, firstly, is that inspect is not really looked upon as a solution by Flourish.  For starters, it's only documented (barely) as an internal method.  Secondly, inspect has always been preferably relegated to a per record basis via ->inspectColumn() on an fActiveRecord instance.  This always seemed rather curious to me as it would seem more common that such information might be needed in a static setting.

Also, I don't think inspect on fORMFile is actually registered as an inspection callback (which seems rather odd).  I would think that it should be.  I tend to find this true about a lot of Flourish, i.e. that the system does not use it's own modularity methods as much as one would hope.

**Comment by khamer** [comment]
@cidic if you can, try not to strip white space when submitting pull requests, as it makes it harder to find what you've changed; just try to stay consistent with how it's formatted.

I agree with @jeffturcotte regarding fPagination; I can see value the enhancement to fPagination.

As for fORMFile, it might make more sense to look into enhancing the meta data from ->inspectColumn() to include some of the file details. A static fORMFile::checkFileColumn() method feels harder to discover. I do agree that fORMFile::inspect is also a little hard to discover, but it wouldn't be hard to write a patch to add in detail from fORMFile::inspect() to ->inspectColumn(), and it would keep the fORMFile::inspect() still mostly an internal method and ->inspectColumn() mostly an external one.

**Comment by mattsah** [comment]
@khamer 

There's nothing special that needs to occur to make fORMFile's values appear in the inspectColumn() methods.  This is actually something Flourish does for everyone else's inspect calls except it's own.

fORMFile just need to be rewritten as more of a plugin that does the following:  http://flourishlib.com/api/fORM#registerInspectCallback

**Comment by mattsah** [comment]
Errr, I take it back. Looking at it, it apparently does do this.  I have never been able to find the info there though.

**Comment by mattsah** [comment]
I should also add, that this still doesn't help when you're looking for it in a static context.  Who wants to instantiate a record just to get some column info that is all static anyway?

**Comment by jeffturcotte** [comment]
@mattsah

**EDIT: Didn't see all the reply(s) before posting. Some of this is still relevant though.**

Maybe I wasn't clear. the `inspect` method on fORMFile _is_ a callback for fORM::registerInspectCallback, hence it needs to have public visibility. The method is marked as internal and documented as such because It shouldn't be used. You would see its effects within the ->inspectColumn() result. fORMFile::inspect is registered as an inspect callback within fORMFile::configureFileUploadColumn.

I agree that there are many scenarios in which it is programmatically bothersome to create an instance just to inspect a column, but this could be alleviated with a helper function:

``` php
function inspect_column($class, $column) {
    $instance = new $class();
    $column = fGrammar::camelize($column);
    call_user_func(array($instance, "inspect{$column}"));
}
```

A more robust version of the functionality provided above should _definitely_ be established within one of the libraries. fORM is probably a good place.

**Comment by cidic** [comment]
I didn't realize it did this. These types of things with callbacks and camel cased function names make tracking this sort of thing down very difficult. I would almost prefer $model->inspectColumn('column_name'); where inspectColumn is actually called that. Then it would be discoverable.

It is also confusing because you have to use an object instance to retrieve meta data that is not (to my understanding) instance specific.

I added the method for this (probably less than brilliant) fActiveRecord Method I use on some of my models.

```
    /**
     * retrives the record as an array of key value pairs
     * @param bool $showFullFilePaths if true the full file path of file columns is returned instead of just the filename stored in the db
     * @return array
     */
    public function toArray($showFullFilePaths = true){
        $result = $this->values;
        foreach ($result as $key => $val) {
            // if is file column return web path and file name
            if (\fORMFile::checkFileColumn($this, $key)) {
                if($showFullFilePaths){
                    $result[$key] = $this->{'prepare' . \fGrammar::camelize($key, TRUE)}(TRUE);
                }
            } else {
                if ($val === null) {
                    $result[$key] = null;
                } else if(!is_numeric($val)){
                    $result[$key] = (string)$val;
                }
            }
        }

        return $result;
    }
```

I also thought that the info returned from `fORMSchema::retrieve()->getColumnInfo('table_name')` would have been the place to find that meta data. I am pretty surprised to find it isn't the same as `$model->inspectColumn()`.

**Comment by wbond** [comment]
I am in favor of making the param for pagination configurable, but not in a static manner.

Can you make a new pull request without whitespace changes that adds a defaulted fourth parameter to the constructor?

**Pull request closed without merging**
